const express = require('express');
const { v4: uuidv4 } = require('uuid');
const { verifyToken, requireRole } = require('../middleware/auth');
const { evaluate, generateWriteup, getQuestionnaire, checkTitleConflicts, CRITERIA } = require('../ai/evaluator');

module.exports = function(db, notify, emailService) {
  const router = express.Router();
  router.use(verifyToken);

  router.get('/questionnaire', (req, res) => res.json({ questions: getQuestionnaire() }));

  // Check title conflicts in real-time
  router.post('/check-title', (req, res) => {
    const { title } = req.body;
    const existingTitles = db.prepare('SELECT title, company_name, year FROM award_titles').all();
    const threshold = parseFloat(process.env.TITLE_SIMILARITY_THRESHOLD) || 0.6;
    const result = checkTitleConflicts(title, existingTitles, threshold);
    res.json(result);
  });

  // ── Validate questionnaire completeness ────────────────
  function validateSubmission(questionnaire, awardTitle) {
    const missing = [];
    if (!awardTitle || awardTitle.trim().length < 3) missing.push('Award Title (must be at least 3 characters)');

    const requiredFields = {
      market_share: 'Market Position rating',
      competitive_edge: 'Competitive advantages description',
      innovation_desc: 'Innovation description',
      innovation_impact: 'Innovation impact rating',
      revenue_growth: 'Revenue growth percentage',
      customer_satisfaction: 'Customer satisfaction score',
      brand_recognition: 'Brand recognition rating',
      years_in_business: 'Years in business'
    };

    for (const [key, label] of Object.entries(requiredFields)) {
      const val = questionnaire[key];
      if (val === undefined || val === null || val === '') {
        missing.push(label);
      }
    }

    // Check text fields have minimum content
    const textFields = {
      competitive_edge: 'Competitive advantages (needs more detail)',
      innovation_desc: 'Innovation description (needs more detail)',
      customer_testimonial: 'Customer success story'
    };
    for (const [key, label] of Object.entries(textFields)) {
      const val = questionnaire[key];
      if (val && typeof val === 'string' && val.trim().length > 0 && val.trim().length < 20) {
        missing.push(`${label} — please provide at least 20 characters`);
      }
    }

    return missing;
  }

  // ── Generate auto-approval justification ───────────────
  function generateJustification(evaluation, companyName, awardTitle, industry) {
    const { totalScore, scores, probability, threshold } = evaluation;
    const ranked = Object.entries(scores).sort((a, b) => b[1].score - a[1].score);
    const top3 = ranked.slice(0, 3);
    const year = new Date().getFullYear();

    return `AUTO-APPROVAL JUSTIFICATION
═══════════════════════════════════════

Company: ${companyName}
Award: ${awardTitle}
Industry: ${industry || 'Not specified'}
Evaluation Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

DECISION: AUTO-APPROVED
Score: ${totalScore}/100 (Threshold: ${threshold}/100)
Probability: ${probability}

RATIONALE:
${companyName} has been auto-approved for "${awardTitle}" based on a comprehensive multi-dimensional AI evaluation. The submission scored ${totalScore}/100, which exceeds the minimum auto-approval threshold of ${threshold}/100.

KEY STRENGTHS:
${top3.map((s, i) => `${i+1}. ${s[1].label}: ${s[1].score}/100 (Weight: ${(s[1].weight*100).toFixed(0)}%)`).join('\n')}

SCORING SUMMARY:
${Object.entries(scores).map(([, v]) => `• ${v.label}: ${v.score}/100 (${(v.weight*100).toFixed(0)}%)`).join('\n')}

TITLE CONFLICT CHECK: No conflicting titles found in the Global Brands Magazine award registry.

This auto-approval was generated by the Insightbridge AI Assessment Engine v2.0. No manual intervention was required as all criteria were met.

Report ID: IBR-${year}-${Date.now().toString(36).toUpperCase()}
───────────────────────────────────────`;
  }

  // Save draft — company or agent
  router.post('/', requireRole('company', 'agent', 'admin'), (req, res) => {
    const { questionnaire, award_category, award_title, company_id } = req.body;
    const isAgent = req.user.role === 'agent' || req.user.role === 'admin';
    const targetUserId = isAgent && company_id ? company_id : req.user.id;

    if (isAgent && company_id) {
      const comp = db.prepare('SELECT id FROM users WHERE id=? AND role=?').get(company_id, 'company');
      if (!comp) return res.status(400).json({ error: 'Invalid company' });
    }

    let submission = db.prepare("SELECT id FROM submissions WHERE user_id=? AND status='draft'").get(targetUserId);
    if (submission) {
      db.prepare('UPDATE submissions SET questionnaire=?,award_category=?,award_title=?,submitted_by=?,submitted_by_role=?,updated_at=CURRENT_TIMESTAMP WHERE id=?')
        .run(JSON.stringify(questionnaire), award_category||'', award_title||'', req.user.id, req.user.role, submission.id);
      return res.json({ id: submission.id, status: 'draft' });
    }

    const id = uuidv4();
    db.prepare(`INSERT INTO submissions (id,user_id,submitted_by,submitted_by_role,questionnaire,award_category,award_title,year,status) VALUES (?,?,?,?,?,?,?,?,?)`)
      .run(id, targetUserId, req.user.id, req.user.role, JSON.stringify(questionnaire), award_category||'', award_title||'', new Date().getFullYear(), 'draft');
    res.json({ id, status: 'draft' });
  });

  // ── Validate before submit ─────────────────────────────
  router.post('/:id/validate', requireRole('company', 'agent', 'admin'), (req, res) => {
    const sub = db.prepare('SELECT * FROM submissions WHERE id=?').get(req.params.id);
    if (!sub) return res.status(404).json({ error: 'Not found' });
    const q = JSON.parse(sub.questionnaire || '{}');
    const missing = validateSubmission(q, sub.award_title);
    res.json({ valid: missing.length === 0, missing });
  });

  // Submit for AI evaluation
  router.post('/:id/submit', requireRole('company', 'agent', 'admin'), (req, res) => {
    const sub = db.prepare('SELECT * FROM submissions WHERE id=?').get(req.params.id);
    if (!sub) return res.status(404).json({ error: 'Not found' });
    if (!['draft', 'revision_requested'].includes(sub.status)) return res.status(400).json({ error: 'Cannot submit in current status' });

    const q = JSON.parse(sub.questionnaire || '{}');
    const user = db.prepare('SELECT * FROM users WHERE id=?').get(sub.user_id);

    // Validate completeness
    const missing = validateSubmission(q, sub.award_title);
    if (missing.length > 0) {
      // Notify about missing data
      notify(sub.user_id, 'warning', 'Incomplete Submission', `Your submission "${sub.award_title || 'Untitled'}" is missing required information: ${missing.slice(0,3).join(', ')}${missing.length > 3 ? ` and ${missing.length-3} more` : ''}.`, `#/submission/${sub.id}`);

      // Send email about missing data
      const loginUrl = `${process.env.BASE_URL || 'https://insightbridge-awards.onrender.com'}/#/dashboard/submission/${sub.id}`;
      emailService.missingData({
        email: user.email,
        companyName: user.company_name,
        contactPerson: user.contact_person,
        awardTitle: sub.award_title || 'Untitled',
        missingFields: missing,
        loginUrl
      });

      // Also email the agent if submitted by agent
      if (sub.submitted_by && sub.submitted_by !== sub.user_id) {
        const agent = db.prepare('SELECT email,contact_person FROM users WHERE id=?').get(sub.submitted_by);
        if (agent) {
          emailService.missingData({
            email: agent.email,
            companyName: user.company_name,
            contactPerson: agent.contact_person,
            awardTitle: sub.award_title || 'Untitled',
            missingFields: missing,
            loginUrl
          });
        }
      }

      return res.status(422).json({ error: 'incomplete', missing, message: `Missing ${missing.length} required fields. Please complete the form.` });
    }

    // AI Evaluate
    const evaluation = evaluate(q);
    const writeup = generateWriteup(q, evaluation, user.company_name, user.industry, sub.award_category, sub.award_title);

    // Check title conflicts
    const existingTitles = db.prepare('SELECT title,company_name,year FROM award_titles').all();
    const titleCheck = checkTitleConflicts(sub.award_title, existingTitles, parseFloat(process.env.TITLE_SIMILARITY_THRESHOLD) || 0.6);

    // Determine status
    let status, approvedAt = null, approvedBy = null, justification = null;
    const threshold = parseInt(process.env.AI_APPROVAL_THRESHOLD) || 65;

    if (titleCheck.hasExact) {
      status = 'title_conflict';
    } else if (evaluation.totalScore >= threshold && !titleCheck.hasSimilar) {
      // Auto-approve by AI
      status = 'ai_approved';
      approvedAt = new Date().toISOString();
      approvedBy = 'AI_EVALUATOR';
      justification = generateJustification(evaluation, user.company_name, sub.award_title, user.industry);
      // Register the title
      if (sub.award_title) {
        db.prepare('INSERT INTO award_titles (id,title,category,company_id,company_name,submission_id,year) VALUES (?,?,?,?,?,?,?)')
          .run(uuidv4(), sub.award_title, sub.award_category, sub.user_id, user.company_name, sub.id, new Date().getFullYear());
      }
    } else if (evaluation.totalScore >= threshold && titleCheck.hasSimilar) {
      status = 'pending_review';
    } else {
      status = 'pending_review';
    }

    const now = new Date().toISOString();
    db.prepare(`UPDATE submissions SET status=?,ai_score=?,ai_probability=?,ai_verdict=?,ai_writeup=?,ai_evaluation=?,title_conflicts=?,submitted_at=?,evaluated_at=?,approved_at=?,approved_by=?,justification=? WHERE id=?`)
      .run(status, evaluation.totalScore, evaluation.probability, evaluation.verdict, writeup, JSON.stringify(evaluation), JSON.stringify(titleCheck), now, now, approvedAt, approvedBy, justification, sub.id);

    db.prepare('INSERT INTO audit_log (action,actor,actor_role,target_id,details) VALUES (?,?,?,?,?)')
      .run('AI_EVALUATION', 'AI_EVALUATOR', 'system', sub.id, `Score:${evaluation.totalScore} Verdict:${evaluation.verdict} Status:${status} Company:${user.company_name}`);

    // ── Notifications & Emails ──────────────────────────
    const loginUrl = `${process.env.BASE_URL || 'https://insightbridge-awards.onrender.com'}/#/dashboard/submission/${sub.id}`;

    if (status === 'ai_approved') {
      notify(sub.user_id, 'approved', 'Award Approved!', `Congratulations! "${sub.award_title || sub.award_category}" has been approved with a score of ${evaluation.totalScore}/100.`, `#/submission/${sub.id}`);
      const approvers = db.prepare("SELECT id FROM users WHERE role='approver'").all();
      approvers.forEach(a => notify(a.id, 'info', 'AI Auto-Approval', `"${sub.award_title}" for ${user.company_name} auto-approved (Score: ${evaluation.totalScore}).`, `#/review/${sub.id}`));

      // Email company
      emailService.autoApproved({
        email: user.email,
        companyName: user.company_name,
        contactPerson: user.contact_person,
        awardTitle: sub.award_title,
        score: evaluation.totalScore,
        justification: justification,
        loginUrl
      });

      // Email agent (if submitted by agent)
      if (sub.submitted_by && sub.submitted_by !== sub.user_id) {
        const agent = db.prepare('SELECT email,contact_person FROM users WHERE id=?').get(sub.submitted_by);
        if (agent) {
          emailService.autoApproved({
            email: agent.email,
            companyName: user.company_name,
            contactPerson: agent.contact_person,
            awardTitle: sub.award_title,
            score: evaluation.totalScore,
            justification: justification,
            loginUrl
          });
        }
      }

    } else if (status === 'pending_review') {
      const reason = titleCheck.hasSimilar ? 'Similar title detected — requires manual review' : `Score ${evaluation.totalScore}/100 is below auto-approval threshold`;
      notify(sub.user_id, 'info', 'Submission Under Review', `Your submission "${sub.award_title || sub.award_category}" is under review. Score: ${evaluation.totalScore}/100.`, `#/submission/${sub.id}`);
      const approvers = db.prepare("SELECT id FROM users WHERE role='approver'").all();
      approvers.forEach(a => notify(a.id, 'action', 'New Submission for Review', `${user.company_name}: "${sub.award_title}" needs review. Score: ${evaluation.totalScore}/100.${titleCheck.hasSimilar ? ' ⚠️ Similar title detected!' : ''}`, `#/review/${sub.id}`));

      // Email company
      emailService.pendingReview({
        email: user.email, companyName: user.company_name, contactPerson: user.contact_person,
        awardTitle: sub.award_title, score: evaluation.totalScore, reason, loginUrl
      });

      // Email agent
      if (sub.submitted_by && sub.submitted_by !== sub.user_id) {
        const agent = db.prepare('SELECT email,contact_person FROM users WHERE id=?').get(sub.submitted_by);
        if (agent) {
          emailService.pendingReview({
            email: agent.email, companyName: user.company_name, contactPerson: agent.contact_person,
            awardTitle: sub.award_title, score: evaluation.totalScore, reason, loginUrl
          });
        }
      }

    } else if (status === 'title_conflict') {
      notify(sub.user_id, 'warning', 'Title Conflict Detected', `The award title "${sub.award_title}" is already in use. Please choose a different title.`, `#/submission/${sub.id}`);
    }

    // Also send a generic "submission received" email to company
    emailService.submissionReceived({
      email: user.email, companyName: user.company_name, contactPerson: user.contact_person,
      awardTitle: sub.award_title, submissionId: sub.id, loginUrl
    });

    res.json({
      id: sub.id, status, justification,
      evaluation: { totalScore: evaluation.totalScore, probability: evaluation.probability, verdict: evaluation.verdict, scores: evaluation.scores },
      writeup, title_conflicts: titleCheck, approved_at: approvedAt
    });
  });

  // Get submissions based on role
  router.get('/mine', (req, res) => {
    let subs;
    if (req.user.role === 'company') {
      subs = db.prepare('SELECT * FROM submissions WHERE user_id=? ORDER BY created_at DESC').all(req.user.id);
    } else if (req.user.role === 'agent') {
      subs = db.prepare('SELECT s.*,u.company_name,u.industry FROM submissions s JOIN users u ON s.user_id=u.id WHERE s.submitted_by=? ORDER BY s.created_at DESC').all(req.user.id);
    } else {
      subs = db.prepare('SELECT s.*,u.company_name,u.industry FROM submissions s JOIN users u ON s.user_id=u.id ORDER BY s.created_at DESC').all();
    }
    subs.forEach(s => { try { s.questionnaire = JSON.parse(s.questionnaire||'{}'); s.ai_evaluation = JSON.parse(s.ai_evaluation||'null'); s.title_conflicts = JSON.parse(s.title_conflicts||'null'); } catch {} });
    res.json({ submissions: subs });
  });

  router.get('/:id', (req, res) => {
    const s = db.prepare('SELECT s.*,u.company_name,u.email,u.industry,u.contact_person,u.country,u.website FROM submissions s JOIN users u ON s.user_id=u.id WHERE s.id=?').get(req.params.id);
    if (!s) return res.status(404).json({ error: 'Not found' });
    if (req.user.role === 'company' && s.user_id !== req.user.id) return res.status(403).json({ error: 'Access denied' });
    try { s.questionnaire = JSON.parse(s.questionnaire||'{}'); s.ai_evaluation = JSON.parse(s.ai_evaluation||'null'); s.title_conflicts = JSON.parse(s.title_conflicts||'null'); } catch {}
    res.json({ submission: s });
  });

  return router;
};
